name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: shivammathur/setup-cpp@v1
        with:
          compiler: clang

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgtest-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Build the library
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Build the main program
        run: |
          clang++ -std=c++17 -o main src/main.cpp -L./lib -lmatrix_multiplication_without_errors

      - name: Run tests
        run: |
          ./build/test/test_matrix_multiplication
